# SQLite version 3.x
#   gem install sqlite3-ruby (not necessary on OS X Leopard)


development_sqlite: &development_sqlite
  adapter: sqlite3
  database: db/development.sqlite3
  timeout: 5000

development:
  <<: *development_sqlite

test:
  adapter: sqlite3
  database: db/test.sqlite3
  timeout: 5000


