environment: oc
http:
    port: 3000
    contextroot: /

log:

    # DEFAULT: log/<environment>.log
    #log-file:

    # Logging level. Log level 0 to 7. 0:OFF, 1:SEVERE, 2:WARNING,
    # 3:INFO (default), 4:FINE, 5:FINER, 6:FINEST, 7:ALL.
    log-level: 3

jruby-runtime-pool:

    initial: 1
    min: 1
    max: 1

daemon:
    enable: true

    # DEFAULT PID tmp/pids/glassfish-<PID>.pid
    #pid:

    # DEFAULT jvm-options: -server -Xmx512m -XX:MaxPermSize=192m -XX:NewRatio=2 -XX:+DisableExplicitGC -Dhk2.file.directory.changeIntervalTimer=6000

    jvm-options: -server -Xmx2500m -Xms64m -XX:PermSize=256m -XX:MaxPermSize=256m -XX:NewRatio=2 -XX:+DisableExplicitGC -Dhk2.file.directory.changeIntervalTimer=6000

