free_prices: &free_prices
  speaker: 0
  organizer: 0
  volunteer: 0
  sponsor: 0

prices: &prices
  early_bird: 1500
  full_price: 2200
  dinner: 500
  <<: *free_prices

development: &development
  prices:
    <<: *prices
  paypal_email: experi_1243951372_biz@iterate.no
  paypal_url: "https://www.sandbox.paypal.com/cgi-bin/webscr"

test:
  prices:
    <<: *prices
  paypal_email: paypal@smidig.no
  paypal_url: "https://www.paypal.com/cgi-bin/webscr"

experimental:
  prices:
    <<: *prices
  paypal_email: experi_1243951372_biz@iterate.no
  paypal_url: "https://www.sandbox.paypal.com/cgi-bin/webscr"


production: &production
  prices:
    <<: *prices
  paypal_email: paypal@smidig.no
  paypal_url: "https://www.paypal.com/cgi-bin/webscr"

staging:
  prices:
    early_bird: 12.50
    full_price: 19.50
    <<: *free_prices
  paypal_email: paypal@smidig.no
  paypal_url: "https://www.paypal.com/cgi-bin/webscr"

  
