production: &production
  early_bird: 1000
  early_bird_dinner: 1500

development:
  early_bird: 1042
  early_bird_dinner: 1542

test:
  <<: *production

experimental:
  <<: *production

staging:
  early_bird: 10
  early_bird_dinner: 15
